/**
 * Explorer Types - Scene and execution type definitions
 *
 * Based on the Claude Code Explorer plan's scene template structure.
 */

// ============================================================================
// Scene Template Types
// ============================================================================

/**
 * Scene identification and metadata.
 */
export interface SceneMetadata {
  id: string;
  act: number;
  title: string;
  durationEstimate?: string;
}

/**
 * Scene purpose and learning outcomes.
 */
export interface ScenePurpose {
  oneLiner: string;
  learningOutcomes: string[];
}

/**
 * Prerequisite scenes and concepts.
 */
export interface ScenePrerequisites {
  scenes: string[];
  concepts: string[];
}

/**
 * File assets used in a scene.
 */
export interface SceneAsset {
  path: string;
  role: string;
  content?: string;
}

/**
 * Mock data for scene execution.
 */
export interface SceneMockData {
  description: string;
  data?: unknown;
}

/**
 * Scene assets including files and mock data.
 */
export interface SceneAssets {
  files: SceneAsset[];
  mockData: SceneMockData[];
}

/**
 * Adjustable parameter for scene variations.
 */
export interface SceneParameter {
  name: string;
  type: 'string' | 'enum' | 'number' | 'boolean';
  default: unknown;
  description: string;
  values?: unknown[]; // For enum types
}

/**
 * Commentary layers for progressive disclosure.
 */
export interface Commentary {
  l1?: string; // Captions - brief inline
  l2?: string; // Narration - step-by-step
  l3?: string; // Deep dive - technical details
}

/**
 * A single execution step in a scene.
 */
export interface ExecutionStep {
  step: number;
  action: string;
  input?: string;
  expectedOutput?: string;
  commentary?: Commentary;
}

/**
 * A scene variation with parameter overrides.
 */
export interface SceneVariation {
  id: string;
  description: string;
  parameterOverrides: Record<string, unknown>;
}

/**
 * Export artifact generated by a scene.
 */
export interface ExportArtifact {
  type: string;
  description: string;
  path?: string;
}

/**
 * Complete scene template definition.
 */
export interface SceneTemplate {
  scene: SceneMetadata;
  purpose: ScenePurpose;
  prerequisites: ScenePrerequisites;
  assets: SceneAssets;
  parameters: SceneParameter[];
  executionSteps: ExecutionStep[];
  variations: SceneVariation[];
  relatedScenes: string[];
  exportArtifacts: ExportArtifact[];
}

// ============================================================================
// Execution State Types
// ============================================================================

/**
 * Current state of scene execution.
 */
export type ExecutionState =
  | 'pending'
  | 'configuring'
  | 'running'
  | 'paused'
  | 'completed'
  | 'error';

/**
 * Runtime parameters with resolved values.
 */
export type ResolvedParameters = Record<string, unknown>;

/**
 * Execution context for a running scene.
 */
export interface ExecutionContext {
  sceneId: string;
  actId: string;
  state: ExecutionState;
  currentStep: number;
  parameters: ResolvedParameters;
  startedAt: string;
  configDir: string;
  eventLogPath: string;
}

/**
 * Result of a completed scene execution.
 */
export interface ExecutionResult {
  sceneId: string;
  success: boolean;
  stepsCompleted: number;
  totalSteps: number;
  durationMs: number;
  events: unknown[];
  error?: {
    step: number;
    message: string;
    code: string;
  };
}

// ============================================================================
// Configuration Types
// ============================================================================

/**
 * Generated Claude Code settings.json structure.
 */
export interface GeneratedSettings {
  hooks?: {
    preToolUse?: HookConfig[];
    postToolUse?: HookConfig[];
    userPromptSubmit?: HookConfig[];
    stop?: HookConfig[];
  };
}

/**
 * Hook configuration for settings.json.
 */
export interface HookConfig {
  matcher: string | { tool?: string; skill?: string };
  command: string;
}

/**
 * Complete generated config for a scene.
 */
export interface GeneratedConfig {
  configDir: string;
  settingsPath: string;
  settings: GeneratedSettings;
  skills: Array<{ path: string; content: string }>;
  agents: Array<{ path: string; content: string }>;
  hooks: Array<{ path: string; content: string }>;
}
